_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
architecture:
    value: ProsusAI/finbert
dataset:
    value: dair-ai/emotion
epochs:
    value: 10
learning_rate:
    value: 2e-05
